[project]
name = "cv-data-summarization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pydantic-ai>=0.0.39",
    "python-docx>=1.1.2",
    "streamlit>=1.43.2",
]
